---

- name: Skype | Add Skype PPA
  apt_repository: repo="ppa:andykimpe/skype" update_cache=yes
  tags:
  - skype
  - apt

- name: Skype | Install Skype
  apt:
    name: "skype"
    state: present
  tags:
  - skype


