---

- name: Skype | Add Skype PPA
  apt_repository: repo="ppa:andykimpe/skype"
  tags:
  - skype
  - apt

- name: Refresh the cache
  apt:
    update_cache: yes
  tags:
  - skype

- name: Skype | Install Skype
  apt:
    name: "skype"
    state: present
  tags:
  - skype


