---

- name: firefox | Install extensions
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - flashplugin-installer
  tags:
  - firefox
  - software
  - desktop

- name: firefox | Create a profile directory
  file:
    path:       /home/{{ project_slug }}/.mozilla/firefox/{{ project_slug }}.default
    state:      directory
    recurse:    yes
    owner:      "{{ project_slug }}"
    group:      "{{ project_slug }}"
  tags:
  - firefox
  - software
  - desktop

- name: firefox | Drop a profiles list and a configuration file
  template:
    src:    "{{ item.src }}"
    dest:   "{{ item.dest }}"
  with_items:
  - src: firefox_profiles.js.j2
    dest: /home/{{ project_slug }}/.mozilla/firefox/profiles.ini
  - src: firefox_prefs.js.j2
    dest: /home/{{ project_slug }}/.mozilla/firefox/{{ project_slug }}.default/prefs.js
  tags:
  - firefox
  - software
  - desktop
