---

# sysadmin

- name: enforce user 'bsfadmin'
  user:
    name:               bsfadmin
    comment:            "Admin"
    uid:                1000
    password:           "$6$MHOUMdoO.tNHLv$aaL6ffPYFGirRo7WmfddNbRhnl11jO6zFOggUohE/j0Ixqmn9Xp2StZ8oilGj7voiGZQcFYAnMDYPX7/XIKd6/"
    groups:             adm,sudo
    state:              present
  tags:
  - users


# template session

- name: Create user 'ideasbox'
  user:
    name:               ideasbox
    comment:            "ideasbox"
    uid:                1010
    password:           "$6$MHOUMdoO.tNHLv$aaL6ffPYFGirRo7WmfddNbRhnl11jO6zFOggUohE/j0Ixqmn9Xp2StZ8oilGj7voiGZQcFYAnMDYPX7/XIKd6/"
    state:              present
  tags:
  - users

- name: Create guest's configuration directory
  file: path=/etc/guest-session state=directory
  tags:
  - users

- name: Symlink 'ideasbox' to guest's skel
  file: src=/home/ideasbox dest=/etc/guest-session/skel state=link
  tags:
  - users

- name: Set up authorized_keys for the bsfadmin user
  authorized_key: user=bsfadmin key="{{ item }}"
  with_file:
    - florian.pub
    - gregoire.pub
    - tom.pub
    - steven.pub
  tags:
  - users

- name: Set up authorized_keys for root user
  authorized_key: user=root key="{{ item }}"
  with_file:
    - florian.pub
    - gregoire.pub
    - tom.pub
    - steven.pub
  tags:
  - users
